version: '3'
services:
  gitbucket:
    image: sk8393/gitbucket:production
    container_name: gitbucket
    deploy:
      replicas: 1
    ports:
      - 8888:8080
      - 29418:29418
    volumes:
      - ./gitbucket/container-volume:/gitbucket

  jenkins:
    image: sk8393/jenkins:production
    container_name: jenkins
    deploy:
      replicas: 1
    ports:
      - '5000:5000'
      - '8889:8080'
    volumes:
      - ./jenkins/container-data-exported-config-file:/root/export
      - ./jenkins/container-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
