#!/bin/bash
source ./variables.part.sh

MAX_VARIABLE_LENGTH=42

SCRIPT_FILE=$(basename $0)
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "SCRIPT_FILE"): ${SCRIPT_FILE}"
SCRIPT_ABSTRACT_PATH=$(cd $(dirname $0); pwd)/${SCRIPT_FILE}
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "SCRIPT_ABSTRACT_PATH"): ${SCRIPT_ABSTRACT_PATH}"

REPOSITORY_BASE_DIRECTORY=$(git rev-parse --show-toplevel)
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "REPOSITORY_BASE_DIRECTORY"): ${REPOSITORY_BASE_DIRECTORY}"

GITBUCKET_RELATED_ASSETS_STORED_IN="gitbucket"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "GITBUCKET_RELATED_ASSETS_STORED_IN"): ${GITBUCKET_RELATED_ASSETS_STORED_IN}"
GITBUCKET_BASE_DIRECTORY="${REPOSITORY_BASE_DIRECTORY}/${GITBUCKET_RELATED_ASSETS_STORED_IN}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "GITBUCKET_BASE_DIRECTORY"): ${GITBUCKET_BASE_DIRECTORY}"

JENKINS_RELATED_ASSETS_STORED_IN="jenkins"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_RELATED_ASSETS_STORED_IN"): ${JENKINS_RELATED_ASSETS_STORED_IN}"
JENKINS_EXPORT_RELATED_ASSETS_STORED_IN="container-data-exported-config-file"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_EXPORT_RELATED_ASSETS_STORED_IN"): ${JENKINS_EXPORT_RELATED_ASSETS_STORED_IN}"
JENKINS_IMPORT_RELATED_ASSETS_STORED_IN="config-file-to-import"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_IMPORT_RELATED_ASSETS_STORED_IN"): ${JENKINS_IMPORT_RELATED_ASSETS_STORED_IN}"
JENKINS_BASE_DIRECTORY="${REPOSITORY_BASE_DIRECTORY}/${JENKINS_RELATED_ASSETS_STORED_IN}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_BASE_DIRECTORY"): ${JENKINS_BASE_DIRECTORY}"
JENKINS_EXPORT_BASE_DIRECTORY="${REPOSITORY_BASE_DIRECTORY}/${JENKINS_RELATED_ASSETS_STORED_IN}/${JENKINS_EXPORT_RELATED_ASSETS_STORED_IN}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_EXPORT_BASE_DIRECTORY"): ${JENKINS_EXPORT_BASE_DIRECTORY}"
JENKINS_IMPORT_BASE_DIRECTORY="${REPOSITORY_BASE_DIRECTORY}/${JENKINS_RELATED_ASSETS_STORED_IN}/${JENKINS_IMPORT_RELATED_ASSETS_STORED_IN}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_IMPORT_BASE_DIRECTORY"): ${JENKINS_IMPORT_BASE_DIRECTORY}"

echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "GITBUCKET_PASSWORD"): ${GITBUCKET_PASSWORD}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "GITBUCKET_PORT"): ${GITBUCKET_PORT}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "GITBUCKET_URL"): ${GITBUCKET_URL}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "GITBUCKET_USER"): ${GITBUCKET_USER}"

echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_LOCALHOST_PORT"): ${JENKINS_LOCALHOST_PORT}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_LOCALHOST_URL"): ${JENKINS_LOCALHOST_URL}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_PASSWORD"): ${JENKINS_PASSWORD}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_PORT"): ${JENKINS_PORT}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_URL"): ${JENKINS_URL}"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "JENKINS_USER"): ${JENKINS_USER}"

VARIABLES_LOADED="1"
echo "$(printf "%${MAX_VARIABLE_LENGTH}s" "VARIABLES_LOADED"): ${VARIABLES_LOADED}"
echo ""
