#!/bin/bash
GITBUCKET_PASSWORD="root"
GITBUCKET_PORT="8888"
GITBUCKET_URL="gitbucket.sk8393.pw"
GITBUCKET_USER="root"

JENKINS_LOCALHOST_PORT="8080"
JENKINS_LOCALHOST_URL="localhost"
JENKINS_PASSWORD="root"
JENKINS_PORT="8889"
JENKINS_URL="jenkins.sk8393.pw"
JENKINS_USER="root"
