version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    deploy:
      replicas: 1
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    deploy:
      replicas: 1
    environment:
      SERVER_NAME: "kibana"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_REQUESTTIMEOUT: "60000"
    ports:
      - "5601:5601"

  postgres:
    image: 'sk8393/postgres:test'
    container_name: postgres
    hostname: postgres
    deploy:
      replicas: 1
    ports:
      - '5432:5432'
#   # Mounting volume on Linux host did not work due to permission issue.
#   # In concrete term, mounted directory was associated with "root" user, and caused following error.
#   # Error: Config owner (postgres:102) and data owner (root:0) do not match, and config owner is not root
#   # Following article describes that this problem does not happen if Docker is running on top of Mac.
#   # https://qiita.com/yohm/items/047b2e68d008ebb0f001
#   volumes:
#     - ../postgres/container-volume:/var/lib/postgresql/10/main

  requester:
    image: 'sk8393/requester:test'
    container_name: requester
    hostname: requester
    deploy:
      replicas: 1
    volumes:
      - /home/ubuntu/cicd/.aws:/root/.aws

  tester:
    image: 'sk8393/tester:test'
    container_name: tester
    hostname: tester
    deploy:
      replicas: 1
    ports:
      - "22222:22"
    volumes:
      - /home/ubuntu/cicd/.aws:/root/.aws

  cloud9:
    image: 'sk8393/cloud9:test'
    container_name: cloud9
    hostname: cloud9
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/cicd/.aws:/root/.aws

  pgadmin4:
    image: dpage/pgadmin4:4.2
    container_name: pgadmin
    ports:
      - 8000:80
    volumes:
      - ../pgadmin/container-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    restart: always
